import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import HighlightDialog from "./components/ui.tsx/highlight-dialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Roboto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-6xl mx-auto pb-4">
          <HighlightDialog/>
          <Header />
          <div className="pt-18">
            {children}
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
